# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import timezone.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_billboard', '0002_add_board_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_board',
            name='date_added',
            field=models.DateTimeField(default=timezone.timezone.now),
        ),
    ]
