# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_billboard', '0003_auto_20180628_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_board',
            name='date_added',
            field=models.CharField(default='2018/06/28', max_length=50),
        ),
    ]
